spring:
  rabbitmq:
    host: 192.168.10.109
    port: 5672
    username: admin
    password: 123456
#    exchange: ${dev.spring.rabbitmq.exchange}
#    routingkey: ${dev.spring.rabbitmq.routingkey}
#    queue: ${dev.spring.rabbitmq.queue}