spring:
  rabbitmq:
    host: 192.168.10.151
    port: 5672
    username: admin
    password: admin
#    exchange: ${dev.spring.rabbitmq.exchange}
#    routingkey: ${dev.spring.rabbitmq.routingkey}
#    queue: ${dev.spring.rabbitmq.queue}